// Shape of public/data/demo-routes.json — the hand-computed hero pair routes.
// Generated by scripts/gen_demo_routes.py (Python, run locally) using Mapbox
// Directions with a perpendicular waypoint injection because Mapbox returns
// only 1 alternative for the 753m hero pair. The waypoint forces a residential
// detour with shared-edge ratio < 0.7 (i.e. visibly divergent on stage).

export interface DemoRouteGeometry {
  type: 'LineString';
  coordinates: [number, number][]; // [lon, lat]
}

export interface DemoRoute {
  description: string;
  distance_m: number;
  duration_s: number;
  geometry: DemoRouteGeometry;
}

export interface DemoRoutesPayload {
  schema_version: number;
  generated_at: string;
  pair: {
    id: string;
    from: { name: string; lon: number; lat: number; zcta: string };
    to:   { name: string; lon: number; lat: number; zcta: string };
  };
  routes: {
    standard: DemoRoute;
    atlas:    DemoRoute & {
      waypoint?: { lon: number; lat: number };
      shared_edge_ratio_with_standard?: number;
    };
  };
}

export async function loadDemoRoutes(): Promise<DemoRoutesPayload> {
  const res = await fetch('/data/demo-routes.json', { cache: 'force-cache' });
  if (!res.ok) {
    throw new Error(`failed to load demo-routes.json: ${res.status}`);
  }
  return res.json();
}
